/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSPINZERO_7D
#define ROOSPINZERO_7D

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooSpinZero_7D : public RooAbsPdf {
public:
    RooSpinZero_7D() {} ; 
    RooSpinZero_7D(const char *name, const char *title,
                RooAbsReal& _m1,
                RooAbsReal& _m2,
                RooAbsReal& _h1,
                RooAbsReal& _h2,
                RooAbsReal& _hs,
                RooAbsReal& _Phi,
                RooAbsReal& _Phi1,
                RooAbsReal& _a1Val,
                RooAbsReal& _phi1Val,
                RooAbsReal& _a2Val,
                RooAbsReal& _phi2Val,
                RooAbsReal& _a3Val,
                RooAbsReal& _phi3Val,
		RooAbsReal& _useGTerm,
		RooAbsReal& _g1Val,
		RooAbsReal& _g2Val,
		RooAbsReal& _g3Val,
		RooAbsReal& _g4Val,
                RooAbsReal& _mZ,
                RooAbsReal& _gamZ,
                RooAbsReal& _mX,
                RooAbsReal& _R1Val,
                RooAbsReal& _R2Val);
    RooSpinZero_7D(const RooSpinZero_7D& other, const char* name=0) ;
    virtual TObject* clone(const char* newname) const { return new RooSpinZero_7D(*this,newname); }
    inline virtual ~RooSpinZero_7D() { }
    
    Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
    Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
    
protected:
    
    RooRealProxy m1 ;
    RooRealProxy m2 ;
    RooRealProxy h1 ;
    RooRealProxy h2 ;
    RooRealProxy hs ;
    RooRealProxy Phi ;
    RooRealProxy Phi1 ;
    RooRealProxy a1Val ;
    RooRealProxy phi1Val ;
    RooRealProxy a2Val ;
    RooRealProxy phi2Val ;
    RooRealProxy a3Val ;
    RooRealProxy phi3Val ;
    RooRealProxy useGTerm ;
    RooRealProxy g1Val ;
    RooRealProxy g2Val ;
    RooRealProxy g3Val ;
    RooRealProxy g4Val ;
    RooRealProxy mZ ;
    RooRealProxy gamZ ;
    RooRealProxy mX ;
    RooRealProxy R1Val ;
    RooRealProxy R2Val ;
    
    Double_t evaluate() const ;
    
private:
    
    ClassDef(RooSpinZero_7D,1) // Your description goes here...
};

#endif
