/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSPINTWOXZSZS_5D
#define ROOSPINTWOXZSZS_5D

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooSpinTwoXZsZs : public RooAbsPdf {
public:
    RooSpinTwoXZsZs() {} ; 
    RooSpinTwoXZsZs(const char *name, const char *title,
                RooAbsReal& _mzz,
                RooAbsReal& _m1,
                RooAbsReal& _m2,
		RooAbsReal& _hs,
                RooAbsReal& _h1,
                RooAbsReal& _h2,
                RooAbsReal& _Phi,
                RooAbsReal& _Phi1,
		RooAbsReal& _c1Val,
		RooAbsReal& _c2Val,
		RooAbsReal& _c3Val,
		RooAbsReal& _c4Val,
		RooAbsReal& _c5Val,
		RooAbsReal& _c6Val,
		RooAbsReal& _c7Val,
		RooAbsReal& _fz1Val,
		RooAbsReal& _fz2Val,
                RooAbsReal& _R1Val,
		RooAbsReal& _R2Val,
		RooAbsReal& _mZ,
   	        RooAbsReal& _gamZ
		);

    RooSpinTwoXZsZs(const RooSpinTwoXZsZs& other, const char* name=0) ;
    virtual TObject* clone(const char* newname) const { return new RooSpinTwoXZsZs(*this,newname); }
    inline virtual ~RooSpinTwoXZsZs() { }
    
    Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
    Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
    
protected:
    
    RooRealProxy mzz ;
    RooRealProxy m1 ;
    RooRealProxy m2 ;
    RooRealProxy hs ;
    RooRealProxy h1 ;
    RooRealProxy h2 ;
    RooRealProxy Phi ;
    RooRealProxy Phi1 ;
    RooRealProxy c1Val;
    RooRealProxy c2Val;
    RooRealProxy c3Val;
    RooRealProxy c4Val;
    RooRealProxy c5Val;
    RooRealProxy c6Val;
    RooRealProxy c7Val;
    RooRealProxy fz1Val ;
    RooRealProxy fz2Val ;
    RooRealProxy R1Val ;
    RooRealProxy R2Val ;
    RooRealProxy mZ;
    RooRealProxy gamZ;
    
    
    Double_t evaluate() const ;
    
private:
    
    ClassDef(RooSpinTwoXZsZs,1) // Your description goes here...
};

#endif
