/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOErfPowPDF
#define ROOErfPowPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooErfPowPdf : public RooAbsPdf {
public:
  RooErfPowPdf() {} ; 
  RooErfPowPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2);
  RooErfPowPdf(const RooErfPowPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooErfPowPdf(*this,newname); }
  inline virtual ~RooErfPowPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooErfPowPdf,1) // Your description goes here...
};
 
#endif
