/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooErfExpPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooErfExpPdf) 

 RooErfExpPdf::RooErfExpPdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _c,
                        RooAbsReal& _offset,
                        RooAbsReal& _width) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   c("c","c",this,_c),
   offset("offset","offset",this,_offset),
   width("width","width",this,_width)
 { 
 } 


 RooErfExpPdf::RooErfExpPdf(const RooErfExpPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   c("c",this,other.c),
   offset("offset",this,other.offset),
   width("width",this,other.width)
 { 
 } 



 Double_t RooErfExpPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return TMath::Exp(c*x)*(1.+TMath::Erf((x-offset)/width))/2. ; 
 } 



 Int_t RooErfExpPdf::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* /*rangeName*/) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   if (matchArgs(allVars,analVars,x)) return 1 ; 
   return 0 ; 
 } 



 Double_t RooErfExpPdf::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   if (code==1) { 
     double minTerm = (TMath::Exp(c*c*width*width/4+c*offset) * 
		       TMath::Erf((2*x.min(rangeName)-c*width*width-
				   2*offset)/2/width) - 
		       TMath::Exp(c*x.min(rangeName)) * 
		       TMath::Erf((x.min(rangeName)-offset)/width) - 
		       TMath::Exp(c*x.min(rangeName)))/-2/c;
     double maxTerm = (TMath::Exp(c*c*width*width/4+c*offset) * 
		       TMath::Erf((2*x.max(rangeName)-c*width*width-
				   2*offset)/2/width) - 
		       TMath::Exp(c*x.max(rangeName)) * 
		       TMath::Erf((x.max(rangeName)-offset)/width) - 
		       TMath::Exp(c*x.max(rangeName)))/-2/c;

     // std::cout << "c: " << c << " offset: " << offset << " width: " << width
     // 	       << '\n'
     // 	       << "maxTerm - minTerm: " << maxTerm << " - " 
     // 	       << minTerm << '\n'
     // 	       << "integral: " << (maxTerm-minTerm) << '\n';
     return (maxTerm-minTerm) ;
   } 
   return 0 ; 
 } 
