/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOQCDPDF
#define ROOQCDPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooQCDPdf : public RooAbsPdf {
public:
  RooQCDPdf() {} ; 
  RooQCDPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1,
	      RooAbsReal& _p2);
  RooQCDPdf(const RooQCDPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooQCDPdf(*this,newname); }
  inline virtual ~RooQCDPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  RooRealProxy p2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooQCDPdf,1) // Your description goes here...
};
 
#endif
