/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSEYMOURPDF
#define ROOSEYMOURPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSeymourPdf : public RooAbsPdf {
public:
  RooSeymourPdf() {} ; 
  RooSeymourPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width);
  RooSeymourPdf(const RooSeymourPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSeymourPdf(*this,newname); }
  inline virtual ~RooSeymourPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooSeymourPdf,1) // Your description goes here...
};
 
#endif
