/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOUser1PDF
#define ROOUser1PDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooUser1Pdf : public RooAbsPdf {
public:
  RooUser1Pdf() {} ; 
  RooUser1Pdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _p0,
	      RooAbsReal& _p1
          );
  RooUser1Pdf(const RooUser1Pdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooUser1Pdf(*this,newname); }
  inline virtual ~RooUser1Pdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy p0 ;
  RooRealProxy p1 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooUser1Pdf,1) // Your description goes here...
};
 
#endif
